### ISSUE TITLE
Request of Bug Tracking List

### ISSUE THREAD

**Issue by ganler** [library-testing/Muffin#2]
Hi Muffin authors, thanks for the great work! In the paper and repo, it says "Muffin can detect 39 new bugs". I am interested in how the bugs look like and am wondering if you can make the bug report/tracking list open, similar to https://github.com/ise-uiuc/FreeFuzz/blob/main/issue_links.csv or https://people.inf.ethz.ch/suz/emi/compcert.html? This will be very helpful for researchers to understand bugs in models training and follow your work!

@River861 @library-testing

**Comment by River861** [comment]
Hi ganler, thanks for your attention!

As we present in the paper, among the 39 new bugs, 18 bugs are inconsistency bugs, including 3 bugs from tensorflow and 15 bugs from theano or CNTK. However, theano and CNTK are not maintained anymore, so we only issued and reported the 3 tensorflow bugs as follow:
* https://github.com/keras-team/keras/issues/15249 （confirmed by developers）
* https://github.com/keras-team/keras/issues/15290
* https://github.com/tensorflow/tensorflow/issues/51681

As for the 21 crash bugs, 20 ones are  from theano and CNTK. But I will still provide you with all the model information, input data, result databases and crash logs in our experiment E1, from which I hope can help you know how the crash bugs look like:
[E1_output.zip](https://drive.google.com/file/d/1_dI0UjHKYosPkrIVC6kQMTB3GkCQHHBc/view?usp=sharing)

Hopefully these information will help you!

@ganler

**Comment by ganler** [comment]
@River861 Thank you for openning the data!
