### ISSUE TITLE
Curious about the definition of learning-related APIs

### ISSUE THREAD

**Issue by YangChenyuan** [library-testing/Muffin#3]
Hello, I am curious about the definition of learning-related APIs. More specially, could you please provide the list of learning-related APIs you defined? Plus, what is the list of APIs that Muffin can cover?

Thanks in advance!

**Comment by library-testing** [comment]
Hi YangChenyuan, thank you for your attention!

We defined the learning-related APIs according to the documentation from Keras. Here is the link from which you  can access the list:
[https://keras.io/api/layers/](url) 

Besides,  the learning-related APIs that Muffin can cover is defined here:
https://github.com/library-testing/Muffin/blob/33d163a1b1970bde3220cfd4c05974e1e3a66c09/utils/utils.py ,
which is almost the same as what keras has defined.

Hopefully these information will help  you! 
@YangChenyuan

**Comment by YangChenyuan** [comment]
Thanks for your kind help!
BTW, what line coverage did you collect, python or c++?

**Comment by library-testing** [comment]
Hi YangChenyuan, we had only collected the python coverage.

We used a python package named `coverage` to calculate the line coverage, the usage of which can be accessed from here:
[https://coverage.readthedocs.io/en/latest/cmd.html](url)

**Comment by YangChenyuan** [comment]
Thanks a lot! I have no other question
