### ISSUE TITLE
Curious about the line coverage

### ISSUE THREAD

**Issue by dengyinlin** [library-testing/Muffin#4]
Hi Muffin authors, thanks for your interesting work!
I am very curious about the line coverage results you reported in the paper: is it c/c++ coverage or python coverage? It would be great if you can also provide the steps for collecting the coverage. Thanks!

**Comment by library-testing** [comment]
Hi dengyinlin, thanks for your attention!
We had only collected the python coverage.

Specifically, as for line coverage, we used a python package named `coverage` , the usage of which can be accessed from here:
[https://coverage.readthedocs.io/en/latest/cmd.html](url)
And we limited the targeted source code using the `--include` option so as to focus on only the learning-related code files.

As for functionality coverage, we simply calculate the coverage of the learning-related APIs, the list of which can be accessed from here:
[https://keras.io/api/layers/](url)

Hopefully these information will help you!
@dengyinlin

**Comment by dengyinlin** [comment]
Thank you very much for the detailed information!
