### ISSUE TITLE
Curious about 4.3.2 Number of detected bugs in Paper

### ISSUE THREAD

**Issue by xuesu** [library-testing/Muffin#5]
Dear Authors of Muffin, Thank you for your quality software and well-written paper; however, I have a question "When an inconsistency is reported, two authors check the corresponding source codes in different libraries and compare the results. If their identical layer produces different results and their implementation ideas are different, the third author will join manual inspection so as to conclude whether the report is true or false positive." why 3 authors are needed to check inconsistency(large value difference in two consecutive layers) across different ML libraries? Is there any special & beneficial design?

**Comment by library-testing** [comment]
Hi xuese, thanks for your attention!

There is a case where the implementation logic of the two libraries on the same layer is not consistent, resulting in a large value difference. In this case, it is possible that both implementations are correct, or that one of them is incorrect. This kind of case (e.g. the “ReLU” bug in Theano) is relatively rare, but it does require a lot of manpower to dig into the source code of the two libraries to confirm whether it is true or false positive. We think it is more adequate to have three authors discuss the source codes.

Hopefully this information will help you!
@xuesu

**Comment by xuesu** [comment]
Thank you for your kind reply!
